/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces.index'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces/': typeof SpacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces': typeof SpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces/': typeof SpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spaces/$slug' | '/spaces/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spaces/$slug' | '/spaces'
  id: '__root__' | '/' | '/spaces/$slug' | '/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpacesSlugRoute: typeof SpacesSlugRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpacesSlugRoute: SpacesSlugRoute,
  SpacesIndexRoute: SpacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
